### ISSUE TITLE
Feature vectors for authors node type of DBLP dataset

### ISSUE THREAD

**Issue by amblee0306** [rayrayraykk/JuSt_walks#1]
Hi there, in JuSt the features vectors of the nodes aren't utilised (the embeddings were used instead) but is it possible that you have the feature vectors for the nodes as well?

Thanks! :)

**Comment by rayrayraykk** [comment]
> 
> 
> Hi there, in JuSt the features vectors of the nodes aren't utilised (the embeddings were used instead) but is it possible that you have the feature vectors for the nodes as well?
> 
> Thanks! :)

The random walk methods don't use features vectors, if you want to use features, you can think about using GNN

**Comment by amblee0306** [comment]
thanks!
